config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  root to: 'landing#index'
  get 'landing/index'

  get 'home', to: 'home#index'

  resources :events do
    member do
      post 'register'
      delete 'unregister'
    end
  end

  resources :venues
  namespace :admin do
    resources :users
  end
  # devise_for :users
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  namespace :api do
    namespace :v1 do
      resources :users
      devise_for :users, controllers: {
        sessions: 'api/v1/sessions',
        registrations: 'api/v1/registrations',
        confirmations: 'api/v1/confirmations'
      }, skip: [:sessions, :registrations, :confirmations], defaults: { format: :json }
      as :user do
        post 'login', to: 'sessions#create', as: :user_session
        delete 'logout', to: 'sessions#destroy', as: :destroy_user_session
        post 'signup', to: 'registrations#create', as: :user_registration
      end
    end
  end
end

app/models/venue.rb
# == Schema Information
#
# Table name: venues
#
#  id            :bigint           not null, primary key
#  address       :string
#  capacity      :integer
#  name          :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  created_by_id :bigint           not null
#
# Indexes
#
#  index_venues_on_created_by_id  (created_by_id)
#
# Foreign Keys
#
#  fk_rails_...  (created_by_id => users.id)
#
class Venue < ApplicationRecord
  belongs_to :created_by, class_name: User.name

  validates :name, :address, :capacity, presence: true

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: %i[ show edit update destroy ]
  verify_authorized

  # GET /venues or /venues.json
  def index
    authorize!

    @venues = Venue.all
  end

  # GET /venues/1 or /venues/1.json
  def show
  end

  # GET /venues/new
  def new
    authorize!

    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues or /venues.json
  def create
    authorize!

    @venue = Venue.new(venue_params)

    @venue.created_by = current_user

    respond_to do |format|
      if @venue.save
        format.html { redirect_to venue_url(@venue), notice: "Venue was successfully created." }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1 or /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to venue_url(@venue), notice: "Venue was successfully updated." }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1 or /venues/1.json
  def destroy
    @venue.destroy

    respond_to do |format|
      format.html { redirect_to venues_url, notice: "Venue was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])

      authorize! @venue
    end

    # Only allow a list of trusted parameters through.
    def venue_params
      params.require(:venue).permit(:name, :address, :capacity, :created_by_id)
    end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_buttons.html.slim
.mt-6.flex.justify-center.items-center.space-x-4
  = link_to venues_path, class: "px-4 py-2 border border-gray-300 rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary" do
    svg.w-5.h-5.mr-2.inline.-mt-1 xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
      path fill-rule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clip-rule="evenodd"
    span Back

  = link_to edit_venue_path(@venue), class: "px-4 py-2 border border-gray-300 rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary" do
    svg.w-5.h-5.mr-2.inline.-mt-1 xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
      path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"
    span Edit

  = button_to venue_path(@venue), method: :delete, class: "px-4 py-2 border border-transparent rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500", data: { confirm: "Are you sure you want to delete this user? This action cannot be undone." } do
    svg.w-5.h-5.mr-2.inline.-mt-1 xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
      path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"
    span Destroy

app/views/venues/_form.html.slim
= form_with(model: @venue, class: "space-y-4 max-w-md mx-auto") do |form|
  .field
    = form.label :name, class: "block text-sm font-medium text-gray-700 mb-1"
    = form.text_field :name, class: "w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-gray-500 focus:border-gray-500", placeholder: "Name"
  .field
    = form.label :address, class: "block text-sm font-medium text-gray-700 mb-1"
    = form.text_field :address, class: "w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-gray-500 focus:border-gray-500", placeholder: "Address"
  .field
    = form.label :capacity, class: "block text-sm font-medium text-gray-700 mb-1"
    = form.number_field :capacity, class: "w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-gray-500 focus:border-gray-500", placeholder: "Capacity"
  .actions
    = form.submit class: "w-full px-4 py-2 text-white bg-primary rounded-md hover:bg-primary-light focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500"

app/views/venues/_venue.html.slim
div id="#{dom_id venue}"
  h2.text-2xl.text-center.font-bold.mb-6.text-gray-800 Venue Details

  .max-w-md.mx-auto.bg-white.shadow-md.rounded-lg.overflow-hidden
    .px-4.py-5.sm:px-6
      h3.text-lg.leading-6.font-medium.text-gray-900 Venue Information
      .border-t.border-gray-200
        dl
          .bg-gray-50.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
            dt.text-sm.font-medium.text-gray-500 Name
            dd.mt-1.text-sm.text-gray-900.sm:mt-0.sm:col-span-2 = venue.name
          .bg-gray-50.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
            dt.text-sm.font-medium.text-gray-500 Address
            dd.mt-1.text-sm.text-gray-900.sm:mt-0.sm:col-span-2 = venue.address
          .bg-white.px-4.py-5.sm:grid.sm:grid-cols-3.sm:gap-4.sm:px-6
            dt.text-sm.font-medium.text-gray-500 Capacity
            dd.mt-1.text-sm.text-gray-900.sm:mt-0.sm:col-span-2 = venue.capacity

app/views/venues/edit.html.slim
h2.text-2xl.text-center.font-bold.mb-6.text-gray-800 Editing Venue

== render 'form', venue: @venue

.mt-4.text-center
  = link_to venues_path, class: "px-4 py-2 border border-gray-300 rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary" do
    svg.w-5.h-5.mr-2.inline.-mt-1 xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
      path fill-rule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clip-rule="evenodd"
    span Back

app/views/venues/index.html.slim
h2.text-2xl.text-center.font-bold.mb-6.text-gray-800 Venues

- if notice.present?
  .bg-green-100.border.border-green-400.text-green-700.px-4.py-3.rounded.relative.mb-4 role="alert"
    = notice

.overflow-x-auto
  table.min-w-full.bg-white.shadow-md.rounded-lg.overflow-hidden
    thead.bg-gray-100
      tr
        th.px-6.py-3.text-left.text-xs.font-medium.text-gray-700.uppercase.tracking-wider Name
        th.px-6.py-3.text-left.text-xs.font-medium.text-gray-700.uppercase.tracking-wider Address
        th.px-6.py-3.text-left.text-xs.font-medium.text-gray-700.uppercase.tracking-wider Capacity
        th.px-6.py-3.text-left.text-xs.font-medium.text-gray-700.uppercase.tracking-wider Created by
        th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider Actions
    tbody.divide-y.divide-gray-200
      - @venues.each do |venue|
        tr
          td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-700 = venue.name
          td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-700 = venue.address
          td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-700 = venue.capacity
          td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-700 = venue.created_by_id
          td.px-6.py-4.whitespace-nowrap.text-sm.font-medium
            = link_to 'Show', venue, class: "text-primary hover:text-primary-light mr-2"
            = link_to 'Edit', edit_venue_path(venue), class: "text-primary hover:text-primary-light mr-2"
            = link_to 'Delete', venue, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-red-600 hover:text-red-900"

.mt-4.text-center
  = link_to 'New Venue', new_venue_path, class: "px-4 py-2 text-white bg-primary rounded-md hover:bg-primary-light focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500"

app/views/venues/new.html.slim
h2.text-2xl.text-center.font-bold.mb-6.text-gray-800 New Venue

== render 'form', venue: @venue

.mt-4.text-center
  = link_to venues_path, class: "px-4 py-2 border border-gray-300 rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary" do
    svg.w-5.h-5.mr-2.inline.-mt-1 xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
      path fill-rule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clip-rule="evenodd"
    span Back

app/views/venues/show.html.slim
p style="color: green" = notice

== render @venue

== render "buttons", venue: @venue